packages:
  all: !include ../_all/all.yaml
  lolin32: !include ../../board-configs/lolin32.yaml

esphome:
  name: doorbell
  # libraries:
  #   - https://github.com/joltwallet/esp_littlefs.git
  includes: 
    - base-configs/doorbell/ding-dong.h

external_components:
  - source:
      type: local
      path: base-configs/doorbell/components
    components: [speaker, i2s_audio]

logger:
ota:

wifi:
  networks:
    <<: !secret WIFI_NETWORKS

status_led:
  pin: GPIO5

i2s_audio:
  i2s_lrclk_pin: GPIO17
  i2s_bclk_pin: GPIO16

speaker:
  - platform: i2s_audio
    dac_type: external
    i2s_dout_pin: GPIO4
    mode: mono

binary_sensor:
  - platform: gpio
    name: bell
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_press: 
      - speaker.play: !lambda return highPCM;
    on_release:
      - speaker.stop
      - speaker.play: !lambda return lowPCM;
