substitutions:
  DEVICE_NAME: remote-dumper
  DEVICE_FRIENDLY_NAME: Remote Dumper
  LOG_LEVEL: VERBOSE

packages:
  esp32-c3: !include board-configs/esp32-c3.yaml

esphome:
  name: ${DEVICE_NAME}
  friendly_name: ${DEVICE_FRIENDLY_NAME}

logger:
  hardware_uart: UART0
  level: ${LOG_LEVEL}
  logs:
    light: INFO

remote_receiver:
  pin: GPIO10
  dump: rc_switch
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 150us
  idle: 4ms
  rmt_channel: 2

light:
  - platform: status_led
    id: status
    internal: true
    output: statusoutput
  - platform: esp32_rmt_led_strip
    internal: true
    rgb_order: GRB
    chipset: WS2812
    pin: GPIO8
    num_leds: 1
    rmt_channel: 0
    name: "Status LED RGB"
    id: statusledlight
    icon: "mdi:led-outline"

output:
  - platform: template
    id: statusoutput
    type: binary
    write_action:
      - if:
          condition:
             lambda: return state > 0;
          then:
            - light.turn_on: 
                id: statusledlight
                red: 1.0
                green: 0.0
                blue: 0.0
                brightness: 30%
          else:
            - light.turn_on: 
                id: statusledlight
                green: 1.0
                red: 0.0
                blue: 0.0
                brightness: 30%
