substitutions:
  CH0_PIN: GPIO18
  CH0_FAULT_PIN: GPIO4

  CH1_PIN: GPIO10
  CH1_FAULT_PIN: GPIO3

packages:
  esp32-c3: !include ../../board-configs/esp32-c3.yaml

esphome:
  name: ${DEVICE_NAME}
  includes:
    - base-configs/dop-lights/light_effects.h

logger:
  level: ${LOG_LEVEL}

wifi:
  networks:
    <<: !secret WIFI_NETWORKS

api:
ota:
  platform: esphome

external_components:
  - source: base-configs/dop-lights/components
    components: [esp32_rmt_led_strip, light]

sensor:
  - pin: ${CH0_FAULT_PIN}
    name: ${DEVICE_NAME} Ch0 Voltage
    <<: !include
      file: sensor_config.yaml
      vars:
        REAL_VOLTS: 5.2
        REPORTED_VOLTS: ${CH0_REPORTED_VOLTS}
  - pin: ${CH1_FAULT_PIN}
    name: ${DEVICE_NAME} Ch1 Voltage
    <<: !include
      file: sensor_config.yaml
      vars:
        REAL_VOLTS: 5.2
        REPORTED_VOLTS: ${CH1_REPORTED_VOLTS}
    <<: !include sensor_config.yaml
  - platform: wifi_signal
    name: ${DEVICE_NAME} WiFi Signal

light:
  - name: ${DEVICE_NAME} Ch0
    pin: ${CH0_PIN}
    rmt_channel: 0
    <<: !include light_config.yaml
  - name: ${DEVICE_NAME} Ch1
    pin: ${CH1_PIN}
    rmt_channel: 1
    <<: !include light_config.yaml
