substitutions:
  CH0_PIN: GPIO18
  CH0_FAULT_PIN: GPIO4

  CH1_PIN: GPIO10
  CH1_FAULT_PIN: GPIO3

packages:
  esp32-c3: !include ../../board-configs/esp32-c3.yaml

esphome:
  name: ${DEVICE_NAME}
  includes:
    - base-configs/dop-lights/light_effects.h

logger:
  level: ${LOG_LEVEL}

wifi:
  networks:
    <<: !secret WIFI_NETWORKS

api:
ota:

external_components:
  - source: base-configs/dop-lights/components
    components: [esp32_rmt_led_strip, light]

sensor:
  - pin: ${CH0_FAULT_PIN}
    name: Ch0 Voltage
    <<: !include sensor_config.yaml
  - pin: ${CH1_FAULT_PIN}
    name: Ch1 Voltage
    <<: !include sensor_config.yaml

light:
  - name: Ch0
    pin: ${CH0_PIN}
    <<: !include light_config.yaml
  - name: Ch1
    pin: ${CH1_PIN}
    <<: !include light_config.yaml
