substitutions:
  CH0_PIN: GPIO18
  CH0_FAULT_PIN: GPIO4

  CH1_PIN: GPIO10
  CH1_FAULT_PIN: GPIO3

packages:
  esp32-c3: !include ../../board-configs/esp32-c3.yaml

esphome:
  name: ${DEVICE_NAME}
  includes:
    - base-configs/dop-lights/light_effects.h

logger:
  level: ${LOG_LEVEL}

wifi:
  networks:
    <<: !secret WIFI_NETWORKS

api:
ota:

external_components:
  - source: base-configs/dop-lights/components
    components: [esp32_rmt_led_strip, light]

sensor:
  - platform: adc
    pin: ${CH0_FAULT_PIN}
    name: Ch0 Voltage
    attenuation: auto
    device_class: Voltage
    filters:
      - multiply: 5.6 # 10k / 2.2k voltage divider

light:
  - platform: esp32_rmt_led_strip
    name: Ch0
    chipset: RDS-RGBW-02
    num_leds: 15
    rgb_order: RGB
    is_rgbw: true
    rmt_channel: 0
    pin: ${CH0_PIN}
    default_transition_length: 0s
    restore_mode: RESTORE_DEFAULT_ON
    effects:
      - addressable_rainbow:
          speed: 10
          width: 15
      - addressable_lambda:
          name: Candy Cane
          update_interval: 1h
          lambda: static_colors(it, {RED, WHITE});
      - addressable_lambda:
          name: Red Green
          update_interval: 1h
          lambda: static_colors(it, {RED, GREEN});
      - addressable_lambda:
          name: Five Color
          update_interval: 1h
          lambda: static_colors(it, {RED, GREEN, BLUE, YELLOW, PURPLE});
      - addressable_rainbow:
          name: ARE GEE BEE
          speed: 10
          width: 150
