platform: esp32_rmt_led_strip
chipset: RDS-RGBW-02
num_leds: 15
rgb_order: RGB
default_transition_length: 0s
restore_mode: RESTORE_DEFAULT_ON
effects:
  - addressable_lambda:
      name: Shimmer
      update_interval: 100ms
      lambda: shimmer(it, current_color);
  - addressable_rainbow:
      speed: 10
      width: 15
  - addressable_lambda:
      name: Candy Cane
      update_interval: 1h
      lambda: static_colors(it, {RED, WHITE});
  - addressable_lambda:
      name: Red Green
      update_interval: 1h
      lambda: static_colors(it, {RED, GREEN});
  - addressable_lambda:
      name: Red, White, Green
      update_interval: 1h
      lambda: static_colors(it, {RED, WHITE, GREEN});
  - addressable_lambda:
      name: Five Color
      update_interval: 1h
      lambda: static_colors(it, {RED, GREEN, BLUE, YELLOW, PURPLE});
  - addressable_lambda:
      name: Seahawks
      update_interval: 1h
      lambda: static_colors(it, {GREEN, BLUE});
  - addressable_rainbow:
      name: ARE GEE BEE
      speed: 10
      width: 150
