---
substitutions:
  uart_tx_pin: GPIO3
  uart_rx_pin: GPIO2
  input_obst_pin: GPIO4
  status_door_pin: GPIO5 # not used
  status_obstruction_pin: GPIO6 # not used
  dry_contact_open_pin: GPIO7 # not used
  dry_contact_close_pin: GPIO8 # not used
  dry_contact_light_pin: GPIO9 # not used

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  project:
    name: ratgdo.esphome
    version: "2.5"

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25board_esp32_d1_mini.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s
  esp32-c3: !include ../../board-configs/esp32-c3-arduino.yaml

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

improv_serial:

wifi:
  networks:
    <<: !secret WIFI_NETWORKS

logger:
